<template>
  <v-container ref="root">
    <h1 id="introduction">API</h1>
    <p>
      In the API, you will discover various options and configurations that you can utilize within
      the library.
    </p>
    <h2 id="excel-table-object">ExcelTable Object</h2>
    <p>
      Certainly! Here's a table describing the properties associated with the root of the
      <b>generateExcel</b> function input:
    </p>
    <TableComponent :rows="dataRel.table.rows"></TableComponent>
    <p>
      These properties allow you to customize various aspects of the Excel file generated by the
      <b>generateExcel</b> function.
    </p>
    <h2 id="styles-object">Styles Object</h2>
    <p>
      To define the styling for your Excel file, you should utilize this option. The
      <b>Styles</b> object allows you to specify various formatting properties that will be applied
      to cells in the generated Excel file. Each property in the object corresponds to a specific
      style element, such as foreground color, font color, font family, size, alignment, border, and
      format. You can customize these properties according to your preferences to achieve the
      desired visual appearance for your Excel document.
    </p>
    <div class="d-flex">
      <div class="pre mb-auto pa-2 mr-1 my-auto">
        <pre>
[key: string]: {
    fg?: string;
    fontColor?:string;
    fontFamily?:string;
    size?: number;
    index?: number;
    alignment?: 
       AlignmentOption;
    border?:BorderOption;
    format: string;
}</pre
        >
      </div>
      <TableComponent :rows="dataRel.styles.rows"></TableComponent>
    </div>
    <h2 id="sheet-object">Sheet Object</h2>
    <p>
      The Sheet object is used to define various options related to a specific sheet within the
      Excel file. It holds a significant role and can be considered as one of the most crucial
      options.
    </p>
    <TableComponent :rows="dataRel.sheet.rows"></TableComponent>

    <p>
      These properties allow you to customize the behavior and appearance of individual sheets
      within the Excel file generated using the library. You can set headers, apply formulas, define
      styles, manage merging cells, specify visibility, and much more to create Excel sheets that
      match your specific requirements.
    </p>
    <h2 id="border-object">Border Object</h2>
    <p>
      If you intend to add borders to your Excel cells, you can utilize this BorderOption object. It
      provides a convenient way to define border properties for various border directions.
    </p>
    <TableComponent :rows="dataRel.border.rows"></TableComponent>
    <p>
      This object allows you to specify the color and style of borders for different directions,
      such as top, left, right, bottom, and full. By incorporating the BorderOption, you can enhance
      the visual appearance of your Excel tables with well-defined and aesthetically pleasing cell
      borders.
    </p>
    <h2 id="formula-object">Formula Object</h2>
    <p>
      The Formula Object provides a way to define formulas for Excel cells. It consists of the
      following properties
    </p>
    <div class="d-flex">
      <div class="pre mb-auto pa-2 mr-1 my-auto">
        <pre>
[insertCell: string]:{ 
    type: FormulaType;
    start: string;
    end: string;
    styleId?: string;
}</pre
        >
      </div>
      <TableComponent :rows="dataRel.formula.rows"></TableComponent>
    </div>
    <p>
      In the above example, we've defined formulas for different cells using the Formula Object. You
      can specify the formula type, start and end cell, and even apply a specific style to the
      formula cells if desired.
    </p>
    <h2 id="alignment-options">Alignment Object</h2>
    <p>
      The library provides several options for aligning cells, allowing you to control how the
      content is displayed within cells. These alignment options can be configured using the
      following properties:
    </p>
    <TableComponent :rows="dataRel.alignment.rows"></TableComponent>
    <p>
      You can use these alignment options to customize the appearance of cell content within your
      Excel sheets. Adjusting these properties allows you to control the positioning, orientation,
      and overall style of the data in your cells.
    </p>
  </v-container>
</template>

<script setup>
import {
  onMounted,
  reactive,
  // reactive,
  ref
} from 'vue'
// import codeJson from '../strings/code.json'
// import CodeSection from '../components/code/codeSection.vue'
// import { ex1, ex } from '../dataset/example'
// import { generateExample } from '../utils/generate'
import { useSelectStore } from '@/stores/select'
import TableComponent from '@/components/table/TableComponent.vue'

const root = ref(null)
const dataRel = reactive({
  table: {
    rows: [
      {
        name: 'notSave?',
        type: 'boolean',
        des: `Controls whether the generated Excel file should be saved.`
      },
      { name: 'creator?', type: 'string', des: `Specifies the creator of the Excel file.` },
      { name: 'created?', type: 'string', des: `Sets the creation date of the Excel file.` },
      { name: 'modified?', type: 'string', des: `Sets the modification date of the Excel file.` },
      {
        name: 'numberOfColumn?',
        type: 'number',
        des: `number	Specifies the number of columns in the Excel file.`
      },
      {
        name: 'createType?',
        type: 'string',
        des: `Specifies the type of creation for the Excel file.`
      },
      {
        name: 'mapSheetDataOption?',
        type: 'any',
        des: `An option to define the type if needed for mapping sheet data.`
      },
      {
        name: '<a href="#styles-object">styles?</a>',
        type: 'Styles',
        des: `Defines the styles to be applied to the Excel cells.`
      },
      {
        name: '<a href="#sheet-object">sheet</a>',
        type: 'Sheet[]',
        des: `An array of sheets containing data and configuration settings.`
      }
    ]
  },
  styles: {
    rows: [
      { name: 'fg?', type: 'string', des: 'Specifies the foreground color of the cell text.' },
      { name: 'fontColor?', type: 'string', des: 'Defines the font color of the cell text.' },
      { name: 'fontFamily?', type: 'string', des: 'Sets the font family for the cell text.' },
      { name: 'size?', type: 'number', des: 'Specifies the font size of the cell text.' },
      { name: 'index?', type: 'number', des: 'Specifies the index of the style.' },
      {
        name: 'alignment?',
        type: 'AlignmentOption',
        des: 'AlignmentOption	Defines the cell alignment properties (horizontal and vertical).'
      },
      { name: 'border?', type: 'BorderOption', des: 'Specifies the border style for the cell.' },
      {
        name: 'format',
        type: 'string',
        des: 'Determines the format of the cell content, such as date, time, currency, etc.'
      }
    ]
  },
  sheet: {
    rows: [
      {
        name: 'withoutHeader?',
        type: 'boolean',
        des: 'Specifies whether the sheet should be generated without a header row.'
      },
      { name: 'formula?', type: 'Formula', des: 'Defines formulas to be applied to the sheet.' },
      { name: 'name?', type: 'string', des: 'Sets the name of the sheet.' },
      {
        name: 'selected?',
        type: 'boolean',
        des: 'Determines if the sheet is selected when the Excel file is opened.'
      },
      { name: 'tabColor?', type: 'string', des: 'Specifies the tab color of the sheet.' },
      { name: 'merges?', type: 'string[]', des: 'Defines merged cell ranges within the sheet.' },
      {
        name: 'headerStyleKey?',
        type: 'string',
        des: 'Sets the style for the header cells using a style ID.'
      },
      {
        name: 'mergeRowDataCondition?',
        type: 'MergeRowDataConditionFunction',
        des: 'Defines a condition for merging rows.'
      },
      {
        name: 'styleCellCondition?',
        type: 'StyleCellConditionFunction',
        des: 'Sets styling conditions for individual cells.'
      },
      {
        name: 'sortAndfilter',
        type: 'SortAndFilter',
        des: 'Defines sorting and filtering options for the sheet.'
      },
      {
        name: 'state',
        type: '"hidden" | "visible"',
        des: 'Determines the visibility of the sheet.'
      },
      {
        name: 'headerRowOption?',
        type: 'any',
        des: 'Allows the definition of header row options (type to be defined if needed).'
      },
      {
        name: 'protectionOption?',
        type: 'ProtectionOption',
        des: 'Specifies protection options for the sheet.'
      },
      { name: 'headerHeight?', type: 'number', des: 'Sets the height of the header row.' },
      { name: 'headers', type: 'Header[]', des: 'Defines the headers for the sheet columns.' },
      { name: 'data', type: 'Data[]', des: 'Provides the data entries for the sheet.' }
    ]
  },
  border: {
    rows: [
      {
        name: 'key',
        type: 'string',
        des: 'BorderDirection value indicating the direction of the border. Possible values include: "full", "top", "left", "right", and "bottom".'
      },
      {
        name: 'color',
        type: 'string',
        des: 'The color of the border. Specify a valid color code or name.'
      },
      {
        name: 'style',
        type: `"slantDashDot"|"dotted"|
"thick"| "hair"|"dashDot"|
"dashDotDot"| "dashed"| "thin"|
"mediumDashDot"| "medium"|
"double"| "mediumDashed"`,
        des: 'The style of the border. Choose from styles such as "slantDashDot", "dotted", "thick", "hair", "dashDot", "dashDotDot", "dashed", "thin", "mediumDashDot", "medium", "double", and "mediumDashed".'
      }
    ]
  },
  formula: {
    rows: [
      {
        name: 'insertCell',
        type: 'string',
        des: 'A string representing the cell where the formula will be inserted.'
      },
      {
        name: 'type',
        type: '"AVERAGE" | "SUM" | "COUNT" | "MAX" | "MIN"',
        des: 'The type of formula to apply. Choose from FormulaType options such as "AVERAGE", "SUM", "COUNT", "MAX", and "MIN".'
      },
      { name: 'start', type: 'string', des: 'The starting cell for the formula range.' },
      { name: 'end', type: 'string', des: 'The ending cell for the formula range.' },
      {
        name: 'styleId',
        type: 'string',
        des: '(Optional) The style ID to be applied to cells containing the formula. Use this if you want to style formula cells.'
      }
    ]
  },
  alignment: {
    rows: [
      {
        name: 'horizontal?',
        type: ' "center" | "left" | "right";',
        des: 'The horizontal alignment of cell content. Choose from "center", "left", or "right".'
      },
      {
        name: 'vertical?',
        type: ' "bottom" | "top" | "bottom";',
        des: 'The vertical alignment of cell content. Choose from "bottom", "top", or "bottom".'
      },
      {
        name: 'wrapText?',
        type: ' "0" | "1";',
        des: 'Whether to wrap text within cells. Use "0" for false or "1" for true.'
      },
      {
        name: 'shrinkToFit?',
        type: ' "0" | "1";',
        des: 'Whether to shrink cell content to fit within the cell. Use "0" for false or "1" for true.'
      },
      {
        name: 'readingOrder?',
        type: ' "1" | "2" | 2 | 1;',
        des: 'The reading order of the cell content. Choose from "1" (left to right) or "2" (right to left).'
      },
      {
        name: 'textRotation?',
        type: ' number;',
        des: 'The degree of text rotation within cells. Can be a number representing the rotation angle.'
      },
      {
        name: 'indent?',
        type: ' number;',
        des: 'The indentation level of cell content. Use a number to specify the indent.'
      },
      {
        name: 'rtl?',
        type: ' boolean;',
        des: 'Whether the cell content should be displayed right-to-left. Use "true" for right-to-left alignment.'
      },
      {
        name: 'ltr?',
        type: ' boolean;',
        des: 'Whether the cell content should be displayed left-to-right. Use "true" for left-to-right alignment.'
      }
    ]
  }
})
let items = []
const select = useSelectStore()
console.log('changes')
select.setNavBar(2)
onMounted(() => {
  const idList = [
    'excel-table-object',
    'styles-object',
    'sheet-object',
    'border-object',
    'formula-object',
    'alignment-options'
  ]
  idList.forEach((v) => {
    // console.log(root.value.)
    select.setNavBar(2)
    items.push(document.querySelector('#' + v))
    console.log(items)
  })
})
window.addEventListener('scroll', function () {
  let selIndex = -1
  let selTop = -1
  let countNotchoosen = 0
  items.forEach((v, index) => {
    const top = v.getBoundingClientRect().top
    if (top >= 0 && (selTop < 0 || selTop > top)) {
      selTop = top
      selIndex = index
    } else {
      countNotchoosen++
    }
    console.log(top, index, 's', countNotchoosen)
  })
  if (countNotchoosen == items.length) {
    selIndex = items.length - 1
  }
  console.log(selIndex, selTop, 'ooo', countNotchoosen)
  select.setSelect(selIndex)
})
</script>
<style scoped>
.pre {
  background: var(--c3);
  color: #fadaa9;
  border-radius: 5px;
}
</style>
